project:
  type: website
  output-dir: docs
  # lib-dir: _layouts
  render: 
    - "*.qmd"
    - "!teaching.qmd"

website:
  title: "Berit E. Batterton"
  description: Academic website of Berit E. Batterton
  site-url: "https://beritbatterton.github.io/"
  favicon: files/Draft_favicon.png
  navbar:
    pinned: true
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - publications.qmd
      - presentations.qmd
      - research.qmd
      - teaching.qmd
    tools:
      - icon: envelope
        href: mailto:b.batterton@utexas.edu
  page-footer:
      background: light
      left: >
        Berit Batterton - <script>document.write(new Date().getFullYear())</script>
      right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/beritbatterton/beritbatterton.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}


format:
  html:
    css: styles.scss
    # mainfont:
    toc: true
    page-layout: full

editor: source

execute:
  enabled: true
  echo: false
  message: false

