project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!teaching.qmd"

website:
  title: "Berit E. Batterton"
  site-url: https://beritbatterton.com
  description: "Academic Website"
  navbar:
    pinned: true
    search: true
    background: ""
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - cv.qmd
    tools:
      - icon: envelope
        href: mailto:b.batterton@utexas.edu
      - icon: twitter
        href: https://x.com/botanyberit
      - icon: bluesky
        href: https://bsky.app/profile/botanyberit.bsky.social
        
  page-footer: "2025- Berit Batterton" 

format:
  html:
    theme: flatly #, litera, lumen, yeti
    css: styles.css
    toc: true

editor: visual

execute:
  echo: false
  message: false

