---
title: "CV"
format: html
toc: true
---

```{r, include = FALSE}
source("pre-render.R")
```

## Education

**PhD (2020 – 2026)** University of Texas at Austin, Marine Science Institute\
Supervisor: Dr. Kenneth H. Dunton\
Thesis: Climate change impacts on carbon and water dynamics in Texas’ estuarine marshes

**BA (2016 – 2020)** University of Pennsylvania, Honors Environmental Science and Biology\
Supervisor: Dr. Jane Dmochowski\
Thesis: Using remote sensing to study effects of dam sediment capacity on seagrass in the Chesapeake Bay

## Professional Experience

**Graduate Research Assistant (2020 – 2025)** University of Texas at Austin, Marine Science\
Supervisor: Dr. Kenneth H. Dunton

**Undergraduate Research Assistant (2019 – 2020)** University of Pennsylvania, Earth & Environmental Sciences\
Supervisor: Dr. Jane Dmochowski

**Undergraduate Research Assistant (2018 – 2019)** University of Pennsylvania, Biology\
Supervisor: Dr. Nick Betley

## Academic Activities

#### Professional Service

**2023-present** Ad-Hoc Reviewer, Aquatic Botany\
**2024** Graduate Education Improvement Committee, University of Texas Marine Science Institute\
**2023–2024** Abstract Review Committee, Society for Wetland Scientists Student Virtual Conference\
**2023-2024** President, University of Texas Marine Science Institute Graduate Student Association\
**2023-2024** Dean’s Office Graduate Council, University of Texas at Austin\
**2023-2024** “Emerging Voices in Botany” Special Issue Award Review Panel, Annals of Botany Plants\
**2022-2023** Vice President, University of Texas Marine Science Institute Graduate Student Association\
**2022** Interim Marine Science Coordinator, University of Texas at Austin\
**2021-2022** Social Coordinator, University of Texas Marine Science Institute Graduate Student Association

#### Professional Societies

-   Ecological Society of America
-   Association for the Sciences of Limnology and Oceanography
-   Coastal and Estuarine Research Federation
-   Ecological Forecasting Initiative
-   Society for Wetland Scientists
-   International Association for Vegetation Science
-   National Marine Educators Association
-   Society for Open, Reliable, and Transparent Ecology and Evolutionary Biology
-   Society for Women in Marine Science
